name: "CI"

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '20 4 */10 * *' #4:20 every 10 days

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out repository under $GITHUB_WORKSPACE
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image that'll build our iso
        run: docker build -t debcdbpoknl-builder .

      - name: Make the output folder
        run: mkdir tmp

      - name: Run the build container
        run: docker run -v $(pwd)/tmp:/tmp debcdbpoknl-builder

      - name: Create/Bump tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: latest-cd-bpokernel

      - name: Delete release and tag
        uses: dev-drprasad/delete-tag-and-release@v0.1.1
        with:
          delete_release: true
          tag_name: latest-cd-bpokernel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: Latest-ish Debian Stable Install CD with backport kernel
          tag: latest-cd-bpokernel
          commit: master
          allowUpdates: true
          replacesArtifacts: true
          draft: false
          prerelease: false
          body: Latest-ish Debian Stable Install CD with backport kernel
          artifacts: "./tmp/simple-cdd-tmp/images/debian-*.iso"
          artifactContentType: application/octet-stream
          token: ${{ secrets.GITHUB_TOKEN }}
